#
# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

name: 'Setup CRIU '
description: 'Download and install CRIU to JDK'
inputs:
  jdk-path:
    description: 'Path to JDK root'
    required: true

runs:
  using: composite
  steps:
    - name: 'Get CRIU URL configuration'
      id: criu_url
      uses: ./.github/actions/config
      with:
        var: LINUX_X64_CRIU_URL

    - name: 'Get CRIU SHA256 configuration'
      id: criu_sha256
      uses: ./.github/actions/config
      with:
        var: LINUX_X64_CRIU_SHA256

    - name: Restore CRIU from cache
      id: criu_cache
      uses: actions/cache@v3
      with:
        path: ~/criu/criu
        key: criu-${{ runner.os }}-${{ steps.criu_url.outputs.value }}

    - name: Download CRIU
      run: |
        CRIU_URL=${{ steps.criu_url.outputs.value }}
        CRIU_FILENAME=$(basename $CRIU_URL)
        wget --progress=dot:mega $CRIU_URL
        echo "${{ steps.criu_sha256.outputs.value }} $CRIU_FILENAME" | sha256sum -c >/dev/null -
        mkdir -p criu/
        tar -xf $CRIU_FILENAME -C criu
        mv $(find criu/ -type f -name criu) criu/criu
      shell: bash
      if: steps.criu.outputs.cache-hit != 'true'

    - name: Setup CRIU
      run: |
        JDK_CRIU=${{ inputs.jdk-path }}/lib/criu
        cp criu/criu $JDK_CRIU
        sudo chown root:root $JDK_CRIU
        sudo chmod u+s $JDK_CRIU
      shell: bash
